# Generated by Django 5.2.1 on 2025-05-18 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_creation', models.IntegerField()),
                ('createur', models.CharField(max_length=100)),
                ('autre', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('annee_creation', models.IntegerField()),
                ('puissance', models.IntegerField()),
                ('poid', models.IntegerField()),
                ('autre', models.TextField(blank=True, null=True)),
                ('marque', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.marque')),
            ],
        ),
    ]
